Update requirements.txt to use dev flask-sqlalchemy
The current stable version 1.0 has issue: AttributeError: 'SessionMaker'
object has no attribute '_model_changes'. See details here:
https://github.com/mitsuhiko/flask-sqlalchemy/pull/89. The issue is
fixed in current master. It seems the author is not going to release any
new version soon. So using master instead of stable release for now.